name: pkmcli ci/cd

on: 
  push: 
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with: 
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Conda env setup
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pkmcli
          environment-file: environment.yaml
          auto-activate-base: false
      # - name: Install dependencies
      #   run: |
      #     # $CONDA is an environment variable pointing to the root of the miniconda directory
      #     $CONDA/bin/conda env update --file environment.yaml --name base --prune
      # - name: Activate env
      #   run: |
      #     # $CONDA is an environment variable pointing to the root of the miniconda directory
      #     $CONDA/bin/conda env update --file environment.yaml --name base --prune
      - name: Install locally
        run: |
          pip3 install .
      - name: Test with pytest
        run: |
          pytest