name: ci-cd

on: 
  push: 
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        run: |
          sudo apt-get install python3
      - name: Conda env setup
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pkmcli
          environment-file: environment.yaml
          auto-activate-base: false
      # - name: Install dependencies
      #   run: |
      #     # $CONDA is an environment variable pointing to the root of the miniconda directory
      #     $CONDA/bin/conda env update --file environment.yaml --name base --prune
      # - name: Activate env
      #   run: |
      #     # $CONDA is an environment variable pointing to the root of the miniconda directory
      #     $CONDA/bin/conda env update --file environment.yaml --name base --prune
      - name: Activate env
        run: |
          conda activate pkmcli
      
      - name: Install locally
        run: |
          pip install --editable .

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest -s